package br.com.findit;

public class DataBase {
	
	public static void createDatabase(){
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabCategory ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabAddress ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabPhone ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabProduct_condition ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabUser ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabProduct ");
		MainActivity.FindItDatabase.execSQL("DROP TABLE tabPost ");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabCategory (id_category integer primary key,cat_desc text)");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabAddress (id_address integer primary key,street text,zip_code text,city text,province text,country text)");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabPhone (id_phone integer primary key,phone_number text)");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabProduct_condition (id_prod_cond integer primary key,prod_cond_desc text)");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabUser (id_user integer primary key,name integer,id_address integer,id_phone integer,foreign key(id_address) references tabAddress (id_address),foreign key (id_phone) references tabPhone (id_phone))");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabProduct (_id integer primary key,description text,add_information text,price double,id_category integer,id_prod_cond integer,foreign key(id_category) references tabCategory (id_category),foreign key ( id_prod_cond ) references tabProduct_condition ( id_prod_cond ))");
		MainActivity.FindItDatabase.execSQL("CREATE TABLE IF NOT EXISTS tabPost ( _id integer, id_user integer, primary key(_id,id_user), foreign key ( id_user ) references tabUser (id_user),foreign key (_id) references tabProduct (_id))");
	}
	
	public static void populateDatabase() {
		
	//tabCategory
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabCategory (id_category, cat_desc) VALUES (1, 'Book')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabCategory (id_category, cat_desc) VALUES (2, 'CD')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabCategory (id_category, cat_desc) VALUES (3, 'DVD')");
		//tabAddress
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (1, 'Ap #146-393 Arcu St.', 'Y2I 9P8', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (2, '1569 Ultrices Rd.', 'O3L 1Z3', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (3, '761-1827 Erat Avenue', 'V6U 6S7', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (4, '117 Blandit Street', 'T1Z 1H1', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (5, 'P.O. Box 439, 5110 Eleifend Av.', 'A0F 7F1', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (6, '335-5313 Vitae Rd.', 'L5S 0W7', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (7, 'P.O. Box 117, 5972 Auctor, Road', 'X2S 6C0', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (8, '777-4603 Mauris Ave', 'K6G 4Q1', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (9, 'P.O. Box 380, 2068 Orci. Rd.', 'V4F 6C7', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (10, '275-7827 Non Rd.', 'Y8X 0I0', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (11, '926-921 Semper, Av.', 'C0W 7I5', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (12, 'P.O. Box 195, 6165 Mauris. Ave', 'C4S 1Q1', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (13, '815-1577 Magna. Street', 'Z1T 5O4', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (14, 'Ap #467-5351 Nec, Av.', 'X0Q 2J3', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (15, '8470 Quis Avenue', 'S3K 1X8', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (16, '902-2025 Dolor St.', 'C1O 4H0', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (17, 'Ap #923-1797 Proin Av.', 'S8B 3O1', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (18, 'Ap #697-2209 Felis Rd.', 'C9I 0E2', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (19, '310-1369 Sed, St.', 'T8H 3D3', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (20, 'Ap #195-7793 Est Rd.', 'U2A 6K1', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (21, '6551 Neque Rd.', 'U3U 1I3', 'Hope', 'British Columbia', 'Canada')");
		/*
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (22, '1677 Ornare St.', 'J8V 7Z0', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (23, 'P.O. Box 816, 4138 Eget St.', 'X9T 2C5', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (24, '7077 Lorem Street', 'E7S 1U5', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (25, 'P.O. Box 381, 372 Suspendisse St.', 'U5C 3M8', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (26, 'Ap #164-6885 Vivamus Avenue', 'S8F 5D7', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (27, 'P.O. Box 210, 5730 Sed Rd.', 'O5M 4B5', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (28, 'P.O. Box 229, 2131 Adipiscing. St.', 'S2Z 5Q3', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (29, 'Ap #994-5576 Augue St.', 'Z0C 8J9', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (30, '753-8736 Ante Av.', 'U3G 5L0', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (31, 'Ap #317-6721 Mi Rd.', 'L6Q 4H0', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (32, '3501 Morbi Ave', 'Z3U 0C7', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (33, 'P.O. Box 882, 3807 Massa. Ave', 'R3R 7D6', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (34, 'P.O. Box 519, 4877 Mauris Ave', 'H5F 4X9', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (35, 'P.O. Box 875, 2381 Et Rd.', 'U9W 2J3', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (36, 'P.O. Box 836, 1528 Egestas Avenue', 'M7C 7D4', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (37, 'Ap #766-9989 Egestas St.', 'U1J 3W9', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (38, '944-5242 Suscipit Road', 'A0Y 3K7', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (39, '8922 Lorem Rd.', 'V2T 7L0', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (40, '712-872 Magnis Avenue', 'F0M 9J8', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (41, 'Ap #772-8111 Molestie St.', 'H1X 7A2', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (42, '578-6514 Tellus St.', 'L8M 9H7', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (43, '950-1998 Id Street', 'C9L 2B4', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (44, 'Ap #872-3868 Sed Avenue', 'P1C 1P5', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (45, '8266 Nam Rd.', 'Z1W 4D9', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (46, 'Ap #603-5333 Pharetra Road', 'R6C 2W1', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (47, 'P.O. Box 774, 3264 Facilisis Rd.', 'N8H 6L5', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (48, '1636 Duis Avenue', 'A1A 1Z7', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (49, 'P.O. Box 471, 8710 Semper Avenue', 'M0I 0Z2', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (50, 'Ap #224-4976 A, Rd.', 'S1G 4T6', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (51, 'P.O. Box 656, 1807 Ante. Av.', 'F5M 9M1', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (52, '2103 Nam Ave', 'B3Y 7R9', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (53, '3025 Non St.', 'Q4G 0O2', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (54, '993-7967 Quis, Road', 'L7L 3Y2', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (55, '592-5023 A, Street', 'L1S 3I9', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (56, 'P.O. Box 226, 4403 Curabitur Avenue', 'L0S 7Y4', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (57, '6803 Enim Rd.', 'J2A 2T8', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (58, '628-8398 Donec Ave', 'D3T 5H6', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (59, '3239 Nullam Rd.', 'O0B 3L2', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (60, '846-6216 Urna. Street', 'G3X 8A2', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (61, 'P.O. Box 842, 6358 At Rd.', 'O2W 9U7', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (62, 'P.O. Box 208, 2399 Proin Street', 'Z1L 6I5', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (63, '6127 Vel Av.', 'R7K 4A8', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (64, 'P.O. Box 749, 9671 Metus Av.', 'P3H 1B8', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (65, 'Ap #314-9189 Cras Rd.', 'Z2U 7E3', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (66, 'P.O. Box 314, 9566 Nibh. Rd.', 'E2W 3W9', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (67, '903-9816 Mus. St.', 'B0J 4Y6', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (68, '127-1000 Tincidunt. Street', 'T8A 7R7', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (69, '751-4666 Neque St.', 'X6D 5H2', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (70, 'Ap #711-9153 Elit. Avenue', 'G3S 3G8', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (71, 'Ap #243-770 Dui Avenue', 'C4I 1A7', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (72, '707-3788 Nec Ave', 'T9E 8I4', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (73, 'Ap #753-1344 Ornare. Av.', 'W7X 7P5', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (74, '3469 Semper Road', 'P6R 9G4', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (75, 'P.O. Box 373, 1263 Amet, Road', 'Z0S 5L0', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (76, 'P.O. Box 666, 5541 Dolor Avenue', 'C8Z 1G1', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (77, 'P.O. Box 689, 820 Erat, Road', 'S0D 8F2', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (78, '6094 In Street', 'F1V 3Z7', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (79, '579-6575 Lorem Rd.', 'N4W 7N6', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (80, '4986 Erat Avenue', 'U1M 4Q7', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (81, '6559 Metus Ave', 'C8L 5M9', 'Abbotsford', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (82, '305-3847 Ut, St.', 'T7A 5E3', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (83, 'P.O. Box 348, 1513 Accumsan Ave', 'V7D 0P5', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (84, '930-6187 Semper Rd.', 'Z0Y 2A4', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (85, 'Ap #314-637 Orci. Avenue', 'Q8P 1V9', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (86, '3407 Diam Street', 'F2J 6Y4', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (87, 'P.O. Box 317, 7065 Cursus, Av.', 'U3N 7N5', 'Chilliwack', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (88, 'Ap #644-7514 Nulla Road', 'G5E 4S3', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (89, '719-4678 Justo Avenue', 'E1B 5A2', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (90, 'Ap #531-4009 Dapibus Street', 'B1T 4O2', 'Hope', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (91, '759-2041 Ligula. St.', 'Y7L 8V1', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (92, 'P.O. Box 808, 6863 Magna. Avenue', 'Q3X 1C7', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (93, '154-5922 A, St.', 'I8T 5F2', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (94, 'P.O. Box 420, 2529 Magna. Street', 'H4A 3G0', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (95, '241-6626 Inceptos Avenue', 'X3W 5B1', 'Vancouver', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (96, 'P.O. Box 673, 3321 Eleifend Street', 'J8K 2C0', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (97, '309-8854 Integer St.', 'Y3B 7A7', 'Surrey', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (98, '2930 Neque Ave', 'D0J 1O7', 'Whistler', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (99, 'P.O. Box 118, 6921 Fames Road', 'C7S 8J7', 'Victoria', 'British Columbia', 'Canada')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabAddress (id_address, street, zip_code, city, province, country) VALUES (100, '7042 Non Av.', 'E1G 9I5', 'Hope', 'British Columbia', 'Canada')");
		*/
		//tabPhone
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (1, '1-234-734-1559')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (2, '1-155-394-9583')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (3, '1-649-392-9613')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (4, '1-136-509-9155')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (5, '1-260-789-1859')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (6, '1-214-143-3305')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (7, '1-708-458-4509')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (8, '1-125-194-0026')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (9, '1-147-551-8958')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (10, '1-428-364-1092')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (11, '1-194-603-9132')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (12, '1-736-582-6611')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (13, '1-563-480-8917')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (14, '1-217-678-9703')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (15, '1-977-726-9821')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (16, '1-177-415-4056')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (17, '1-878-635-4324')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (18, '1-721-594-0833')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (19, '1-931-773-2237')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (20, '1-815-668-2125')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (21, '1-597-747-1554')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (22, '1-858-125-3477')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (23, '1-368-735-6569')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (24, '1-119-883-5080')");
		/*
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (25, '1-576-378-8136')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (26, '1-862-735-2018')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (27, '1-910-899-1490')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (28, '1-548-275-0574')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (29, '1-250-523-0541')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (30, '1-432-511-3363')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (31, '1-517-324-8395')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (32, '1-711-864-1795')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (33, '1-839-271-3149')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (34, '1-590-213-6066')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (35, '1-648-725-1320')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (36, '1-903-921-0525')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (37, '1-574-696-9665')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (38, '1-330-202-6268')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (39, '1-359-742-8571')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (40, '1-129-589-1758')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (41, '1-481-401-5741')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (42, '1-677-642-7375')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (43, '1-588-527-3459')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (44, '1-288-329-5769')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (45, '1-927-782-0658')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (46, '1-306-259-8933')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (47, '1-952-784-7323')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (48, '1-416-195-3918')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (49, '1-849-454-3446')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (50, '1-832-101-5857')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (51, '1-289-898-3285')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (52, '1-269-205-6400')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (53, '1-183-494-4429')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (54, '1-248-228-0618')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (55, '1-225-245-7097')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (56, '1-105-434-8891')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (57, '1-805-728-5247')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (58, '1-160-684-1541')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (59, '1-351-895-3842')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (60, '1-123-605-4579')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (61, '1-386-344-7691')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (62, '1-727-906-5459')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (63, '1-652-912-4682')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (64, '1-610-344-6116')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (65, '1-389-170-6242')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (66, '1-307-509-7565')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (67, '1-727-751-2233')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (68, '1-962-860-8332')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (69, '1-653-403-3780')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (70, '1-452-138-2605')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (71, '1-191-378-2515')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (72, '1-870-111-4482')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (73, '1-528-722-5586')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (74, '1-186-213-9391')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (75, '1-968-170-1240')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (76, '1-592-475-6304')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (77, '1-103-624-9288')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (78, '1-475-373-2957')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (79, '1-907-244-7088')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (80, '1-689-941-4433')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (81, '1-370-898-2287')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (82, '1-978-792-1729')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (83, '1-588-572-6260')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (84, '1-597-687-4092')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (85, '1-890-669-8771')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (86, '1-729-667-8295')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (87, '1-355-113-8648')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (88, '1-927-983-9716')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (89, '1-898-845-5385')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (90, '1-810-422-7181')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (91, '1-974-762-0692')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (92, '1-381-265-7295')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (93, '1-877-910-1819')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (94, '1-106-473-6896')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (95, '1-124-240-7136')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (96, '1-713-504-5137')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (97, '1-238-875-1441')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (98, '1-143-567-5398')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (99, '1-160-410-8722')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPhone (id_phone, phone_number) VALUES (100, '1-535-312-8363')");
		*/
		//product condition
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct_condition (id_prod_cond, prod_cond_desc) VALUES (1, 'Very Bad')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct_condition (id_prod_cond, prod_cond_desc) VALUES (2, 'Bad')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct_condition (id_prod_cond, prod_cond_desc) VALUES (3, 'OK')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct_condition (id_prod_cond, prod_cond_desc) VALUES (4, 'Good')");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct_condition (id_prod_cond, prod_cond_desc) VALUES (5, 'Very Good')");
		//tabUser
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (1, 'Astra H. Rivas', 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (2, 'Liberty Garcia', 2, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (3, 'Vaughan F. Palmer', 3, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (4, 'Alma E. Savage', 4, 4)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (5, 'Vernon R. Holloway', 5, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (6, 'Grady Wiley', 6, 6)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (7, 'Audra Hebert', 7, 7)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (8, 'Cameron W. Dudley', 8, 8)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (9, 'Shea R. Carr', 9, 9)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (10, 'Penelope Raymond', 10, 10)");
		/*
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (11, 'Maia Whitfield', 11, 11)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (12, 'Shaeleigh Craig', 12, 12)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (13, 'Nathaniel Evans', 13, 13)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (14, 'Talon A. Fitzgerald', 14, 14)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (15, 'Bo Frost', 15, 15)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (16, 'Eagan Spencer', 16, 16)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (17, 'Kelly Copeland', 17, 17)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (18, 'Keith P. Campbell', 18, 18)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (19, 'Derek O. Dotson', 19, 19)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (20, 'Taylor Moreno', 20, 20)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (21, 'Madonna Forbes', 21, 21)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (22, 'Zahir Mills', 22, 22)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (23, 'Cheyenne I. Kennedy', 23, 23)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (24, 'Imelda Solis', 24, 24)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (25, 'Penelope Z. Randolph', 25, 25)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (26, 'Thor Henson', 26, 26)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (27, 'Davis Bell', 27, 27)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (28, 'Phyllis G. Gillespie', 28, 28)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (29, 'Vielka Lancaster', 29, 29)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (30, 'Clayton Buchanan', 30, 30)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (31, 'Nehru X. Fitzgerald', 31, 31)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (32, 'Porter Sampson', 32, 32)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (33, 'Clementine Schmidt', 33, 33)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (34, 'Martin L. Davenport', 34, 34)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (35, 'Mary Y. Pacheco', 35, 35)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (36, 'Quon Cortez', 36, 36)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (37, 'Chancellor Duncan', 37, 37)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (38, 'Anika Mueller', 38, 38)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (39, 'Wayne Allen', 39, 39)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (40, 'Harding Brooks', 40, 40)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (41, 'Megan C. Sandoval', 41, 41)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (42, 'Ulysses Ruiz', 42, 42)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (43, 'Jamalia Grant', 43, 43)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (44, 'Jenna Henson', 44, 44)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (45, 'Virginia Cox', 45, 45)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (46, 'Vincent T. Vega', 46, 46)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (47, 'Sopoline Burton', 47, 47)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (48, 'Evan K. Kirby', 48, 48)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (49, 'Tara J. Warner', 49, 49)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (50, 'Wyatt Burch', 50, 50)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (51, 'Desiree Hanson', 51, 51)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (52, 'Daquan X. Wright', 52, 52)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (53, 'Hammett White', 53, 53)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (54, 'Basia A. Avery', 54, 54)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (55, 'Trevor Wilson', 55, 55)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (56, 'Jenna Rosales', 56, 56)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (57, 'Zephr Hendricks', 57, 57)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (58, 'Montana T. Hicks', 58, 58)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (59, 'Ria Ashley', 59, 59)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (60, 'Otto Baxter', 60, 60)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (61, 'Aquila Morgan', 61, 61)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (62, 'Amber V. Hogan', 62, 62)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (63, 'Paula Hanson', 63, 63)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (64, 'Keane P. Best', 64, 64)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (65, 'Brianna Golden', 65, 65)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (66, 'Heather Dorsey', 66, 66)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (67, 'Brenna Gilbert', 67, 67)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (68, 'Constance Kane', 68, 68)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (69, 'Phillip Powell', 69, 69)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (70, 'Kelsey S. Navarro', 70, 70)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (71, 'Bevis D. Wilcox', 71, 71)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (72, 'Destiny Sexton', 72, 72)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (73, 'Jacqueline P. Espinoza', 73, 73)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (74, 'Jesse Bennett', 74, 74)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (75, 'Finn Z. Dodson', 75, 75)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (76, 'Nevada R. Simon', 76, 76)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (77, 'Montana Daniels', 77, 77)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (78, 'Felicia P. Cooley', 78, 78)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (79, 'Asher H. Wolf', 79, 79)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (80, 'Jacob Fisher', 80, 80)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (81, 'Aurelia Y. Zimmerman', 81, 81)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (82, 'Wyatt Matthews', 82, 82)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (83, 'Chantale Hicks', 83, 83)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (84, 'Ray Blevins', 84, 84)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (85, 'Ocean Curtis', 85, 85)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (86, 'Duncan Harmon', 86, 86)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (87, 'Tamekah Vargas', 87, 87)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (88, 'Lacey Vincent', 88, 88)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (89, 'Zephr Baldwin', 89, 89)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (90, 'Isabelle Jefferson', 90, 90)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (91, 'Bryar J. Graves', 91, 91)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (92, 'Doris T. Mcdonald', 92, 92)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (93, 'Emma H. Malone', 93, 93)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (94, 'Laurel Conley', 94, 94)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (95, 'Mara Chavez', 95, 95)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (96, 'Ina U. Waters', 96, 96)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (97, 'James B. Blankenship', 97, 97)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (98, 'Tanner Slater', 98, 98)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (99, 'Roth L. Butler', 99, 99)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabUser (id_user, name, id_address, id_phone) VALUES (100, 'Ivana Mayo', 100, 100)");
		*/
		//tabProduct
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (1, 'Les Miserables', 'Author: lalalalalalalalala Year: 1996', 3.0, 1, 4)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (2, 'The Little Prince', 'Author: lalalalalalalalalaYear: 1996', 51.5, 1, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (3, 'A Tale of Two Cities ', 'Author: lalalalalalalalalaYear: 1996', 35.5, 1, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (4, 'The Art of War', 'Author: lalalalalalalalalaYear: 1996', 60.0, 1, 4)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (5, 'The Little Prince', 'Author: lalalalalalalalalaYear: 1996', 3.0, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (6, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 11.5, 1, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (7, 'Life of Pi', 'Author: lalalalalalalalalaYear: 1996', 53.0, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (8, 'Crime and Punishment', 'Author: lalalalalalalalalaYear: 1996', 35.9, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (9, 'Life of Pi', 'Author: lalalalalalalalalaYear: 1996', 35.5, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (10, 'Crime and Punishment', 'Author: lalalalalalalalalaYear: 1996', 35.5, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (11, 'The Little Prince', 'Author: lalalalalalalalalaYear: 1996', 24.36, 1, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (12, 'The Hobbit & The Lord of the Rings', 'Author: lalalalalalalalalaYear: 1996', 45.0, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (13, 'The Art of War', 'Author: lalalalalalalalalaYear: 1996', 5.5, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (14, 'Crime and Punishment', 'Author: lalalalalalalalalaYear: 1996', 45.0, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (15, 'Anne of Green Gables', 'Author: lalalalalalalalalaYear: 1996', 35.62, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (16, 'Anne of Green Gables', 'Author: lalalalalalalalalaYear: 1996', 12.25, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (17, 'Crime and Punishment', 'Author: lalalalalalalalalaYear: 1996', 26.0, 1, 4)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (18, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 5.5, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (19, 'The Boy in the Striped Pajamas', 'Author: lalalalalalalalalaYear: 1996', 26.3, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (20, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 34.99, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (21, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 26.3, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (22, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 24.05, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (23, 'The Notebook', 'Author: lalalalalalalalalaYear: 1996', 51.5, 1, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (24, 'The Art of War', 'Author: lalalalalalalalalaYear: 1996', 34.99, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (25, 'The Notebook', 'Author: lalalalalalalalalaYear: 1996', 60.0, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (26, 'The Hobbit', 'Author: lalalalalalalalalaYear: 1996', 26.3, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (27, 'A Tale of Two Cities ', 'Author: lalalalalalalalalaYear: 1996', 18.3, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (28, 'The Hobbit & The Lord of the Rings', 'Author: lalalalalalalalalaYear: 1996', 37.2, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (29, 'The Notebook', 'Author: lalalalalalalalalaYear: 1996', 60.0, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (30, 'Les Miserables', 'Author: lalalalalalalalalaYear: 1996', 60.0, 1, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (31, 'The Boy in the Striped Pajamas', 'Author: lalalalalalalalalaYear: 1996', 24.36, 1, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (32, 'Les Miserables', 'Author: lalalalalalalalalaYear: 1996', 27.0, 1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabProduct (_id, description, add_information, price, id_category, id_prod_cond) VALUES (33, 'Water for Elephants', 'Author: lalalalalalalalalaYear: 1996', 12.25, 1, 5)");
		//tabPost
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (1, 1)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (3, 2)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (5, 3)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (7, 4)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (9, 5)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (11, 6)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (13, 7)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (15, 8)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (17, 9)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (19, 10)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (21, 11)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (23, 12)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (25, 13)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (27, 14)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (29, 15)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (31, 16)");
		MainActivity.FindItDatabase.execSQL("INSERT INTO tabPost (_id, id_user) VALUES (33, 17)");
}
	
	
	 
	
	
}
